---
# Project information
site_name: opsworks_ruby
site_url: https://opsworks_ruby.rzegocki.pl/
site_author: Igor Rzegocki
site_description: >-
  Manage OpsWorks instances with ease
# Repository
repo_name: ajgon/opsworks_ruby
repo_url: https://github.com/ajgon/opsworks_ruby
# Development
dev_addr: 0.0.0.0:8000

# Copyright
copyright: Copyright &copy; 2016 - 2021 Igor Rzegocki

nav:
  - 'Home': index.md
  - 'User Documentation':
    - 'Getting Started': getting-started.md
    - 'Troubleshooting': troubleshooting.md
  - 'Cookbook Documentation':
    - 'Supported Technologies': support.md
    - 'Requirements': requirements.md
    - 'Attributes': attributes.md
    - 'Recipes': recipes.md
  - 'About opsworks_ruby':
    - 'Contributing': contributing.md
    - 'Author and Contributors': team.md
    - 'Changelog': changelog.md
    - 'License': license.md

plugins:
  - search

extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - toc:
      permalink: true
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: red
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
